version: '3'

vars:
  SRC_DIR: src
  TEST_DIR: tests
  BENCH_DIR: benchmarks
  # Platform-specific library names
  LIB_NAME:
    sh: |
      case "$(uname -s)" in
        Linux*)   echo "libocsv.so" ;;
        Darwin*)  echo "libocsv.dylib" ;;
        MINGW*|MSYS*|CYGWIN*) echo "ocsv.dll" ;;
        *) echo "libocsv.so" ;;
      esac
  PLATFORM:
    sh: |
      case "$(uname -s)" in
        Linux*)   echo "Linux" ;;
        Darwin*)  echo "macOS" ;;
        MINGW*|MSYS*|CYGWIN*) echo "Windows" ;;
        *) echo "Unknown" ;;
      esac
  ARCH:
    sh: uname -m

tasks:
  build:
    desc: Build release library (optimized, cross-platform)
    cmds:
      - echo "Building for {{.PLATFORM}} ({{.ARCH}})..."
      - odin build {{.SRC_DIR}} -out:{{.LIB_NAME}} -build-mode:shared -o:speed -show-timings
      - echo "✓ Built {{.LIB_NAME}}"
    sources:
      - "{{.SRC_DIR}}/**/*.odin"
    generates:
      - "{{.LIB_NAME}}"

  build-dev:
    desc: Build debug library (with debug symbols, cross-platform)
    cmds:
      - echo "Building DEBUG for {{.PLATFORM}} ({{.ARCH}})..."
      - odin build {{.SRC_DIR}} -out:{{.LIB_NAME}} -build-mode:shared -debug -show-timings
      - echo "✓ Built {{.LIB_NAME}} (debug)"
    sources:
      - "{{.SRC_DIR}}/**/*.odin"
    generates:
      - "{{.LIB_NAME}}"

  test:
    desc: Run all tests
    cmds:
      - odin test {{.TEST_DIR}} -all-packages
    deps: [build-dev]

  test-leaks:
    desc: Run tests with memory leak detection
    cmds:
      - odin test {{.TEST_DIR}} -all-packages -define:USE_TRACKING_ALLOCATOR=true
    deps: [build-dev]

  bench:
    desc: Run performance benchmark
    cmds:
      - bun run {{.BENCH_DIR}}/benchmark.js
    deps: [build]

  check:
    desc: Check code without building
    cmds:
      - odin check {{.SRC_DIR}} -all-packages

  clean:
    desc: Clean build artifacts (all platforms)
    cmds:
      - rm -f *.so *.dylib *.dll *.a *.lib
      - rm -rf tests.bin tests.bin.dSYM

  fmt:
    desc: Format Odin source code
    cmds:
      - odin fmt {{.SRC_DIR}}
      - odin fmt {{.TEST_DIR}}

  all:
    desc: Build, test, and benchmark
    cmds:
      - task: build
      - task: test
      - task: bench

  info:
    desc: Show platform and build information
    cmds:
      - echo "Platform - {{.PLATFORM}}"
      - echo "Architecture - {{.ARCH}}"
      - echo "Library name - {{.LIB_NAME}}"
      - odin version

  help:
    desc: Show available tasks
    cmds:
      - task --list
