name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14, ubuntu-latest]
        include:
          - os: macos-14
            lib_name: libcsv.dylib
            platform: macOS
          - os: ubuntu-latest
            lib_name: libcsv.so
            platform: Linux

    runs-on: ${{ matrix.os }}
    name: Build & Test (${{ matrix.platform }})
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download LLVM (MacOS ARM)
        if: matrix.os == 'macos-14'
        run: |
          brew update
          brew install llvm@20
          echo "$(brew --prefix llvm@20)/bin" >> $GITHUB_PATH

      - name: Download LLVM (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 20
          echo "/usr/lib/llvm-20/bin" >> $GITHUB_PATH

      - name: Clone and Build Odin
        run: |
          cd /tmp
          git clone --depth=1 https://github.com/odin-lang/Odin.git
          cd Odin
          ./build_odin.sh release
          echo "/tmp/Odin" >> $GITHUB_PATH

      - name: Verify Odin installation
        run: |
          odin version
          odin report

      - name: Build library
        run: odin build src -build-mode:shared -out:${{ matrix.lib_name }} -o:speed

      - name: Verify library exists
        run: |
          if [ -f "${{ matrix.lib_name }}" ]; then
            echo "✓ Library built successfully: ${{ matrix.lib_name }}"
            ls -lh ${{ matrix.lib_name }}
          else
            echo "✗ Library not found!"
            exit 1
          fi

      - name: Run tests
        run: odin test tests -all-packages

      - name: Run tests with memory tracking
        run: odin test tests -all-packages -debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ocsv-${{ matrix.platform }}-${{ github.sha }}
          path: ${{ matrix.lib_name }}
          retention-days: 7

  lint:
    name: Lint & Format Check
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download LLVM (Ubuntu)
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 20
          echo "/usr/lib/llvm-20/bin" >> $GITHUB_PATH

      - name: Clone and Build Odin
        run: |
          cd /tmp
          git clone --depth=1 https://github.com/odin-lang/Odin.git
          cd Odin
          ./build_odin.sh release
          echo "/tmp/Odin" >> $GITHUB_PATH

      - name: Check code
        run: odin check src -all-packages

      - name: Check tests
        run: odin check tests -all-packages
